---
env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
root: true
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - args: after-used
      argsIgnorePattern: _
      ignoreRestSiblings: false
      vars: all
      varsIgnorePattern: _
  '@typescript-eslint/no-use-before-define':
    - error
  '@typescript-eslint/prefer-nullish-coalescing': error
  '@typescript-eslint/prefer-optional-chain': error
  eqeqeq:
    - error
    - smart
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  import/order:
    - 2
    - alphabetize:
        order: asc
  import/prefer-default-export: off
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  no-use-before-define: off
  no-void:
    - error
    - allowAsStatement: true
  padding-line-between-statements:
    - error
    - blankLine: always
      next: return
      prev: '*'
  sort-imports: 0
